# Generated by Django 3.0.6 on 2020-05-27 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_auto_20200527_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crashlist',
            name='day_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crash_list_in_day_start', to='machines.Day'),
        ),
        migrations.AlterField(
            model_name='stoptimelist',
            name='day_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_time_list_in_day_start', to='machines.Day'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='day_start',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='todo_list_in_day_start', to='machines.Day'),
        ),
        migrations.AlterField(
            model_name='value',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values_in_day', to='machines.Day'),
        ),
    ]
