# Generated by Django 3.0.6 on 2020-05-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_auto_20200528_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='services',
            field=models.ManyToManyField(related_name='services_todo_list', through='machines.ServiceToDoList', to='machines.ServiceName'),
        ),
    ]
