# Generated by Django 3.0.7 on 2020-06-28 19:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0004_auto_20200528_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('code', models.CharField(choices=[('STR', 'Start'), ('MSG', 'Message'), ('FNS', 'Finish')], default='MSG', max_length=3)),
                ('dt_create', models.DateTimeField(default=datetime.datetime(2020, 6, 28, 19, 41, 34, 609804, tzinfo=utc))),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
