# Generated by Django 3.0.7 on 2020-06-28 19:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='message',
            name='crash_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crash_list_messages', to='machines.CrashList'),
        ),
        migrations.AlterField(
            model_name='message',
            name='dt_create',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 28, 19, 47, 16, 549200, tzinfo=utc)),
        ),
    ]
