# Generated by Django 3.0.7 on 2020-06-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_auto_20200628_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dt_create',
            field=models.DateTimeField(),
        ),
    ]
