# Generated by Django 3.0.7 on 2020-06-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_auto_20200628_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='do_not_agree',
            field=models.BooleanField(default=False),
        ),
    ]
