# Generated by Django 3.0.7 on 2020-07-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massmeters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AddField(
            model_name='massmeter',
            name='sn',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
