# Generated by Django 3.0.7 on 2020-07-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massmeters', '0001_squashed_0004_auto_20200710_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmeter',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
