# Generated by Django 3.0.7 on 2020-07-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massmeters', '0002_auto_20200710_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DFL', 'Черновик'), ('ACT', 'Действующее'), ('HST', 'Архив')], default='DFL', max_length=3),
        ),
        migrations.AlterField(
            model_name='event',
            name='mass_object',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
